blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/skyeBreach/UEE-Pathfinders-Helpdesk/discussions
      about: Ask your questions (and answer others) about this project
      
